### ISSUE TITLE
Add some documentation

### ISSUE THREAD

**Issue by Wavesonics** [Jummit/Godot-Replicator-Node-Plugin#1]
Would love some documentation on how this works, and how to implement it in a project.

**Comment by Jummit** [comment]
Will do!
There is some documentation in the Replicator script:
https://github.com/Jummit/Godot-Replicator-Node-Plugin/blob/92ab5a6ea0b702ae8cf633841f5c2bb354d9f885/addons/replicator/Replicator.gd#L3-L10
But I'll put a tutorial in the readme.

**Comment by Jummit** [comment]
Fixed in 264b633a2956d3a9a27c7b8e4e425ae85ae5aee1
