### ISSUE TITLE
Remote Spawner - cleanlier naming solution

### ISSUE THREAD

**Issue by paultech** [Jummit/Godot-Replicator-Node-Plugin#4]
Currently, in use is a signal to rename the node to remove the '@' symbols added to indicate it's been spawned from a script.
https://github.com/Jummit/replicator-node/blob/a8a52345a7abde29ad19ef0ec20b6aada81813ab/addons/replicator/remote_spawner.gd#L10

https://github.com/Jummit/replicator-node/blob/a8a52345a7abde29ad19ef0ec20b6aada81813ab/addons/replicator/remote_spawner.gd#L41-L44

However if 
https://github.com/Jummit/replicator-node/blob/a8a52345a7abde29ad19ef0ec20b6aada81813ab/addons/replicator/remote_spawner.gd#L30

is changed to 
`	multiplayer.root_node.get_node(parent).add_child(instance,true)`

We could avoid signal usage. (Second parameter to add_child is `legible_unique_name`) 

Can submit a PR but it's only a few line change

**Comment by Jummit** [comment]
This doesn't work for nodes that have been added programmatically without `legible_unique_name`. If the server spawns a bullet and it gets named "Bullet@213", there is no way to replicate that name to the clients, and the hack is still necessary.

So there are three solutions:

1. the current approach
2. use `legible_unique_name` when adding nodes
3. make a PR to Godot that makes `legible_unique_name` true by default

Thanks a lot for the suggestion!

**Comment by wyltk-pfleming** [comment]
I had not considered that use case, that makes sense now.
 
I'd maintain current approach for best user workflow. Pardon the noise.

**Comment by paultech** [comment]
I had not considered that use case, that makes sense now.

I'd maintain current approach for best user workflow. Pardon the noise.
